### ISSUE TITLE
TV input is missing

### ISSUE THREAD

**Issue by daciand** [AntonioMeireles/homebridge-vieramatic#2] opened 2020-01-19 12:07 UTC
Hi, it's me again :)

Is it possible to have "TV" in the input list? The plugin managed to autodetect a lot of applications but no "TV" option is present there.

Thanks!

**Comment by AntonioMeireles** [comment] 2020-01-19 12:23
Oh, sure it is... forgot that as i have no use for it :( 

Other than this - everything behaving for you ?

Thanks, once again, for your patience!

**Comment by AntonioMeireles** [comment] 2020-01-19 13:08
@daciand 

Hi, 

can you give a try to latest iteration i just pushed;-) (and close this if things behave as expected) 

Thanks once again!

**Comment by daciand** [comment] 2020-01-19 14:05
I surely will, just give me a second and I'll get back at you

**Comment by daciand** [comment] 2020-01-19 14:10
Unfortunately, now it just crashes upon starting homebridge:
```
Jan 19 16:09:27 raspberrypi homebridge[14072]: found a Panasonic VIErA TV (TX-55FZ800E) at 192.168.0.153.
Jan 19 16:09:28 raspberrypi homebridge[14072]: found Panasonic VIErA TV (TX-55FZ800E) requires crypto for comunication.
Jan 19 16:09:29 raspberrypi homebridge[14072]: TypeError: Cannot read property 'groups' of null
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at findValue (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:13:65)
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at callback (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:398:23)
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at /usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:312:7
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at Vieramatic.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:63:28)
Jan 19 16:09:29 raspberrypi homebridge[14072]: TypeError: Cannot read property 'applications' of undefined
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at Vieramatic.addAccessory (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:78:45)
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at Vieramatic.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:64:14)
Jan 19 16:09:29 raspberrypi homebridge[14072]:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
Jan 19 16:09:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 19 16:09:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.


```

**Comment by AntonioMeireles** [comment] 2020-01-19 14:14
humm. 

a) is TV (powered) on and not in standby ?
b) (if yes to above) can you rm in your homebridge dir the `{persist,accessories}`dirs ? and then try again ?

Thanks again for your patience

**Comment by daciand** [comment] 2020-01-19 14:21
TV is powered, but in stand by (still it respond to ping requests). But with previous version it worked just fine.
I'll try to delete the content of those 2 folders.

**Comment by AntonioMeireles** [comment] 2020-01-19 14:22
ok. FWIW there's an annoying 'feature' in Pana's API - app's list fetch only works if TV is ON (and not just in stand by). looking into it.

**Comment by daciand** [comment] 2020-01-19 14:24
Now homebridge started, but I still get some errors within the log:
```
Jan 19 16:23:08 raspberrypi homebridge[14540]: found a Panasonic VIErA TV (TX-55FZ800E) at 192.168.0.153.
Jan 19 16:23:08 raspberrypi homebridge[14540]: [1/19/2020, 16:23:08] [Temperature & Humidity (kitchen)] Start scanning.
Jan 19 16:23:08 raspberrypi homebridge[14540]: found Panasonic VIErA TV (TX-55FZ800E) requires crypto for comunication.
Jan 19 16:23:08 raspberrypi homebridge[14540]: TypeError: Cannot read property 'groups' of null
Jan 19 16:23:08 raspberrypi homebridge[14540]:     at findValue (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:13:65)
Jan 19 16:23:08 raspberrypi homebridge[14540]:     at callback (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:398:23)
Jan 19 16:23:08 raspberrypi homebridge[14540]:     at /usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:312:7
Jan 19 16:23:08 raspberrypi homebridge[14540]:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
Jan 19 16:23:08 raspberrypi homebridge[14540]:     at Vieramatic.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:63:28)
Jan 19 16:23:09 raspberrypi homebridge[14540]: [1/19/2020, 16:23:09] [PanasonicVieraTV] DidFinishLaunching
```
At least it doesn't crash anymore.

**Comment by AntonioMeireles** [comment] 2020-01-19 14:25
is that with TV powered ON ?

**Comment by daciand** [comment] 2020-01-19 14:30
So, I've stopped homebridge, powered the TV, empty dirs, and restarted homebridge.
No more errors now but all accessories added through homebridge are now in not responding state :(

**Comment by AntonioMeireles** [comment] 2020-01-19 14:31
looking into it. (but cannot reproduce atm - albeit i've found other bugs :( )

**Comment by daciand** [comment] 2020-01-19 15:07
I also had to start over again with setting up homebridge accessories. No idea what happened.
Please reply as soon as you managed to fix those known bugs. Thanks! :)

**Comment by AntonioMeireles** [comment] 2020-01-19 15:48
OK. if homebridge got restarted and TV was in standby app list wouldn't be refreshed which caused all sorts of undesired effects. now, if TV in standby we'll recover previously known app list which should get things a fair bit more resilient. 

Test please when you have some spare time. Add *again* **THANKS**!

**Comment by AntonioMeireles** [comment] 2020-01-29 19:32
hi, any update on your side on this ?

Thanks in advance!

**Comment by daciand** [comment] 2020-02-03 20:01
hi,
sorry for being offline for a while! 
everything seems really fine right now, it works as expected, using latest version 0.5.82.

Thank you again for this magnificent plugin!

**Closed** 2020-02-03 20:02 UTC
